apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sykmeldinger
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.nav.no/syk/sykmeldinger'
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /syk/sykmeldinger/api/internal/is_alive
  readiness:
    path: /syk/sykmeldinger/api/internal/is_ready
  gcp:
    buckets:
      - name: sykmeldinger-prod-debug-bucket-todo-delete
        retentionPeriodDays: 2
        lifecycleCondition:
          age: 7
          createdBefore: 2020-01-01
          numNewerVersions: 2
          withState: ANY
  env:
    - name: NEXT_PUBLIC_BASE_PATH
      value: /syk/sykmeldinger
    - name: RUNTIME_ENVIRONMENT
      value: 'production'
    - name: SYKMELDINGER_BACKEND
      value: 'https://sykmeldinger-backend.nav.no'
    - name: FLEX_GATEWAY_ROOT
      value: 'https://flex-gateway.nav.no'
    - name: LOGIN_SERVICE_URL
      value: 'https://loginservice.nav.no/login'
    - name: LOGIN_SERVICE_REDIRECT_URL
      value: 'https://www.nav.no/syk/sykmeldinger'
    - name: AMPLITUDE_ENABLED
      value: 'true'
    - name: SYKEPENGESOKNAD_URL
      value: 'https://www.nav.no/syk/sykepengesoknad'
    - name: SYKEFRAVAER_ROOT
      value: 'https://www.nav.no/syk/sykefravaer'
    - name: DITT_NAV_ROOT
      value: 'https://www.nav.no/person/dittnav'
    - name: ASSET_PREFIX
      value: 'https://teamsykmelding-static-files.nav.no/sykmeldinger'
    - name: SENTRY_ENABLED
      value: 'true'
