apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://sykmeldinger.labs.nais.io/"
  replicas:
    min: 1
    max: 1
  liveness:
    path: /is_alive
  readiness:
    path: /is_ready
  env:
    - name: DECORATOR_URL
      value: https://www.nav.no/dekoratoren
    - name: RUNTIME_ENVIRONMENT
      value: labs-demo
    - name: AMPLITUDE_ENABLED
      value: 'false'
