apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sykmeldinger
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www-gcp.dev.nav.no/syk/sykmeldinger'
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /syk/sykmeldinger/api/internal/is_alive
  readiness:
    path: /syk/sykmeldinger/api/internal/is_ready
  env:
    - name: NEXT_PUBLIC_BASE_PATH
      value: /syk/sykmeldinger
    - name: RUNTIME_ENVIRONMENT
      value: 'dev'
    - name: SYKMELDINGER_BACKEND
      value: 'https://sykmelding-gateway.dev.nav.no/sykmeldinger-backend'
    - name: FLEX_GATEWAY_ROOT
      value: 'https://flex-gateway.dev.nav.no'
    - name: LOGIN_SERVICE_URL
      value: 'https://loginservice.dev.nav.no/login'
    - name: LOGIN_SERVICE_REDIRECT_URL
      value: 'https://www-gcp.dev.nav.no/syk/sykmeldinger'
    - name: AMPLITUDE_ENABLED
      value: 'false'
    - name: SYKEPENGESOKNAD_URL
      value: 'https://www-gcp.dev.nav.no/syk/sykepengesoknad'
    - name: SYKEFRAVAER_ROOT
      value: 'https://www-gcp.dev.nav.no/syk/sykefravaer'
    - name: DITT_NAV_ROOT
      value: 'https://person.dev.nav.no/person/dittnav/'
    - name: ASSET_PREFIX
      value: 'https://teamsykmelding-static-files.dev.nav.no/sykmeldinger'
