apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykefravaer
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 3000
  env:
    - name: DECORATOR_URL
      value: https://www.nav.no/dekoratoren
  ingresses:
    - "https://sykmeldinger.labs.nais.io/"
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  accessPolicy:
    outbound:
      external:
        - host: www.nav.no
        - host: syfoapi.nav.no