apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: {{appname}}-demo
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
    branchState: {{branchState}}
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - {{ingress}}
  replicas:
    min: {{replicas}}
    max: {{replicas}}
  liveness:
    path: /syk/sykmeldinger/api/internal/is_alive
  readiness:
    path: /syk/sykmeldinger/api/internal/is_ready
  env:
    - name: NEXT_PUBLIC_BASE_PATH
      value: /syk/sykmeldinger
    - name: DECORATOR_URL
      value: https://www.nav.no/dekoratoren
    - name: RUNTIME_ENVIRONMENT
      value: demo
    - name: AMPLITUDE_ENABLED
      value: 'false'
    - name: SYKEFRAVAER_ROOT
      value: 'https://demo.ekstern.dev.nav.no/syk/sykefravaer'
