apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  webproxy: false
  ingresses:
    - "https://tjenester-q1.nav.no/sykefravaer/sykmeldinger"
    - "https://sykmeldinger.nais.oera-q.local/"
