apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sykmeldinger
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://sykmeldinger.labs.nais.io/'
  replicas:
    min: 1
    max: 1
  liveness:
    path: /syk/sykmeldinger/api/internal/is_alive
  readiness:
    path: /syk/sykmeldinger/api/internal/is_ready
  env:
    - name: NEXT_PUBLIC_BASE_PATH
      value: /syk/sykmeldinger
    - name: DECORATOR_URL
      value: https://www.nav.no/dekoratoren
    - name: RUNTIME_ENVIRONMENT
      value: labs
    - name: AMPLITUDE_ENABLED
      value: 'false'
    - name: SYKEFRAVAER_ROOT
      value: 'https://ditt-sykefravaer.labs.nais.io/syk/sykefravaer'
