apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sykmeldinger
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www-gcp.dev.nav.no/syk/sykmeldinger'
  idporten:
    enabled: true
    sidecar:
      enabled: true
  tokenx:
    enabled: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  accessPolicy:
    outbound:
      rules:
        - application: sykmeldinger-backend
        - application: flex-syketilfelle
          namespace: flex
  liveness:
    path: /syk/sykmeldinger/api/internal/is_alive
  readiness:
    path: /syk/sykmeldinger/api/internal/is_ready
  env:
    - name: NEXT_PUBLIC_BASE_PATH
      value: /syk/sykmeldinger
    - name: RUNTIME_ENVIRONMENT
      value: 'dev'
    - name: SYKMELDINGER_BACKEND
      value: 'http://sykmeldinger-backend'
    - name: FLEX_SYKETILFELLE
      value: 'http://flex-syketilfelle.flex'
    - name: SYKMELDINGER_BACKEND_SCOPE
      value: 'dev-gcp:teamsykmelding:sykmeldinger-backend'
    - name: FLEX_SYKETILFELLE_BACKEND_SCOPE
      value: 'dev-gcp:flex:flex-syketilfelle'
    - name: AMPLITUDE_ENABLED
      value: 'true'
    - name: SYKEPENGESOKNAD_URL
      value: 'https://www-gcp.dev.nav.no/syk/sykepengesoknad'
    - name: SYKEFRAVAER_ROOT
      value: 'https://www-gcp.dev.nav.no/syk/sykefravaer'
    - name: MIN_SIDE_ROOT
      value: 'https://www.dev.nav.no/minside/'
    - name: ASSET_PREFIX
      value: 'https://cdn.nav.no/teamsykmelding/sykmeldinger'
    - name: DISPLAY_EGENMELDING
      value: 'true'
