apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykmeldinger
  namespace: default
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://tjenester-q1.nav.no/sykmeldinger"
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /is_alive
  readiness:
    path: /is_ready
  env:
    - name: DECORATOR_URL
      value: https://www-q1.nav.no/dekoratoren
    - name: RUNTIME_ENVIRONMENT
      value: q1
