apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sykmeldinger
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.nav.no/syk/sykmeldinger'
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /syk/sykmeldinger/api/**
  tokenx:
    enabled: true
  prometheus:
    enabled: true
    path: /syk/sykmeldinger/api/internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  replicas:
    min: 2
    max: 7
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 160m
      memory: 390Mi
  liveness:
    path: /syk/sykmeldinger/api/internal/is_alive
  readiness:
    path: /syk/sykmeldinger/api/internal/is_ready
  preStopHook:
    http:
      path: /syk/sykmeldinger/api/internal/pre_stop
  accessPolicy:
    outbound:
      rules:
        - application: sykmeldinger-backend
        - application: flex-syketilfelle
          namespace: flex
        - application: nav-dekoratoren
          namespace: personbruker
        - application: flexjar-backend
          namespace: flex
      external:
        - host: teamsykmelding-unleash-api.nav.cloud.nais.io
  env:
    - name: SYKMELDINGER_BACKEND
      value: 'http://sykmeldinger-backend'
    - name: SYKMELDINGER_BACKEND_SCOPE
      value: 'prod-gcp:teamsykmelding:sykmeldinger-backend'
    - name: FLEX_SYKETILFELLE
      value: 'http://flex-syketilfelle.flex'
    - name: FLEX_SYKETILFELLE_BACKEND_SCOPE
      value: 'prod-gcp:flex:flex-syketilfelle'
    - name: FLEXJAR
      value: 'http://flexjar-backend.flex'
    - name: FLEXJAR_BACKEND_SCOPE
      value: 'prod-gcp:flex:flexjar-backend'
    - name: UNLEASH_SERVER_API_URL
      value: 'https://teamsykmelding-unleash-api.nav.cloud.nais.io/api'
  envFrom:
    - secret: sykmeldinger-unleash-secrets
