export const PASIENT_ELDRE_ENN_70 = 'PASIENT_ELDRE_ENN_70';
export const UKJENT_DIAGNOSEKODETYPE = 'UKJENT_DIAGNOSEKODETYPE';
export const UGYLDIG_KODEVERK_FOR_BIDIAGNOSE = 'UGYLDIG_KODEVERK_FOR_BIDIAGNOSE';
export const UGYLDIG_REGELSETTVERSJON = 'UGYLDIG_REGELSETTVERSJON';
export const BEHANDLER_IKKE_GYLDIG_I_HPR = 'BEHANDLER_IKKE_GYLDIG_I_HPR';
export const BEHANDLER_MANGLER_AUTORISASJON_I_HPR = 'BEHANDLER_MANGLER_AUTORISASJON_I_HPR';
export const BEHANDLER_IKKE_LE_KI_MT_TL_FT_I_HPR = 'BEHANDLER_IKKE_LE_KI_MT_TL_FT_I_HPR';
export const BEHANDLER_SUSPENDERT = 'BEHANDLER_SUSPENDERT';
