export type ExpectedToggles = (typeof EXPECTED_TOGGLES)[number]
export const EXPECTED_TOGGLES = [
    'SYKMELDINGER_FLEXJAR_KVITTERING',
    'SYKMELDINGER_LIST_VIEW_DATA_FETCHING',
    'SYKMELDINGER_FISKERE',
] as const
