export type ExpectedToggles = (typeof EXPECTED_TOGGLES)[number]
export const EXPECTED_TOGGLES = ['SYKMELDINGER_FLEXJAR_KVITTERING', 'SYKMELDINGER_ANNET_BONUSSPORSMAL', 'SYKMELDINGER_ENDRE_ARBEIDSSITUASJON'] as const
