import './globals.css'

import Script from 'next/script'
import React, { PropsWithChildren } from 'react'

import RscDecorator from './RSCDecorator'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }: PropsWithChildren): Promise<JSX.Element> {
    return (
        <html lang="en">
            <head>
                <Script
                    src={`${process.env.NEXT_PUBLIC_BASE_PATH ?? ''}/api/public-env`}
                    strategy="beforeInteractive"
                />
            </head>
            <body>
                {/* @ts-expect-error Wrong JSX typing for RSC */}
                <RscDecorator
                    env={createDecoratorEnv()}
                    chatbot={true}
                    context={'privatperson'}
                    // breadcrumbs={createInitialServerSideBreadcrumbs(ctx.pathname, ctx.query)}
                >
                    {children}
                </RscDecorator>
            </body>
        </html>
    )
}

function createDecoratorEnv(): 'dev' | 'prod' {
    if (process.env.NODE_ENV === 'development') {
        // Blir statisk kompilert i GHA så må hentes defra
        return 'prod'
    }

    switch (process.env.RUNTIME_ENVIRONMENT) {
        case 'local':
        case 'test':
        case 'dev':
            return 'dev'
        case 'demo':
        case 'production':
            return 'prod'
        default:
            throw new Error(`Unknown RUNTIME_ENVIRONMENT: ${process.env.RUNTIME_ENVIRONMENT}`)
    }
}
