apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sykmeldinger
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.ekstern.dev.nav.no/syk/sykmeldinger'
  idporten:
    enabled: true
    sidecar:
      enabled: true
  tokenx:
    enabled: true
  prometheus:
    enabled: true
    path: /syk/sykmeldinger/api/internal/prometheus
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: sykmeldinger-backend
        - application: flex-syketilfelle
          namespace: flex
        - application: nav-dekoratoren
          namespace: personbruker
        - application: flexjar-backend
          namespace: flex
      external:
        - host: teamsykmelding-unleash-api.nav.cloud.nais.io
        - host: flex-syketilfelle.flex
        - host: ekstern.dev.nav.no
        - host: dev.nav.no
        - host: cdn.nav.no
  liveness:
    path: /syk/sykmeldinger/api/internal/is_alive
  readiness:
    path: /syk/sykmeldinger/api/internal/is_ready
  preStopHook:
    http:
      path: /syk/sykmeldinger/api/internal/pre_stop
  env:
    - name: SYKMELDINGER_BACKEND
      value: 'http://sykmeldinger-backend'
    - name: SYKMELDINGER_BACKEND_SCOPE
      value: 'dev-gcp:teamsykmelding:sykmeldinger-backend'
    - name: FLEX_SYKETILFELLE
      value: 'http://flex-syketilfelle.flex'
    - name: FLEX_SYKETILFELLE_BACKEND_SCOPE
      value: 'dev-gcp:flex:flex-syketilfelle'
    - name: FLEXJAR
      value: 'http://flexjar-backend.flex'
    - name: FLEXJAR_BACKEND_SCOPE
      value: 'dev-gcp:flex:flexjar-backend'
    - name: UNLEASH_SERVER_API_URL
      value: 'https://teamsykmelding-unleash-api.nav.cloud.nais.io/api'
  envFrom:
    - secret: sykmeldinger-unleash-secrets
