apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: sykmeldinger
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - 'https://www.nav.no/syk/sykmeldinger'
  idporten:
    enabled: true
    sidecar:
      enabled: true
      resources:
        requests:
          cpu: 150m
  tokenx:
    enabled: true
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /syk/sykmeldinger/api/internal/is_alive
  readiness:
    path: /syk/sykmeldinger/api/internal/is_ready
  accessPolicy:
    outbound:
      rules:
        - application: sykmeldinger-backend
        - application: flex-syketilfelle
          namespace: flex
      external:
        - host: flex-syketilfelle.flex
        - host: nav.no
        - host: cdn.nav.no
  envFrom:
    - configmap: sykmeldinger-config
  env:
    - name: SYKMELDINGER_BACKEND
      value: 'http://sykmeldinger-backend'
    - name: FLEX_SYKETILFELLE
      value: 'http://flex-syketilfelle.flex'
    - name: SYKMELDINGER_BACKEND_SCOPE
      value: 'prod-gcp:teamsykmelding:sykmeldinger-backend'
    - name: FLEX_SYKETILFELLE_BACKEND_SCOPE
      value: 'prod-gcp:flex:flex-syketilfelle'
