apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: {{appname}}-demo
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
    branchState: {{branchState}}
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - {{ingress}}
  replicas:
    min: {{replicas}}
    max: {{replicas}}
  liveness:
    path: /syk/sykmeldinger/api/internal/is_alive
  readiness:
    path: /syk/sykmeldinger/api/internal/is_ready
  accessPolicy:
    outbound:
      external:
        - host: nav.no
        - host: demo.ekstern.dev.nav.no
      rules:
        - application: nav-dekoratoren
          namespace: personbruker
  envFrom:
    - configmap: sykmeldinger-config
