name: Deploy to labs-gcp
on:
    push:
        branches: ["*"]
env:
    IMAGE: docker.pkg.github.com/${{ github.repository }}/sykmeldinger:${{ github.sha }}
jobs:
    build-push-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1
            - name: Use Node 
              uses: actions/setup-node@v1
              with:
                node-version: "12.x"
            - name: Install dependencies for server
              run: |
                npm install
              working-directory: ./server
            - name: Run tests for server
              run: |
                npm run test
              working-directory: ./server
            - name: Install dependencies for client
              run: |
                npm install
              working-directory: ./client
            #- name: Run tests for client
            #  env:
            #    CI: true
            #  run: |
            #    npm run test
            #  working-directory: ./client
            - name: Build server
              run: |
                npm run compile
              working-directory: ./server
            - name: Build client
              env:
                REACT_APP_IS_GCP_LABS: "true"
                REACT_APP_SYKEFRAVAER_ROOT: "/"
                REACT_APP_SYKMELDINGER_ROOT: "/"
                REACT_APP_LOGINSERVICE_URL: "https://loginservice-q.nav.no/login"
                REACT_APP_SM_REGISTER_URL: "https://syfosmregisterproxy-q.nav.no"
                REACT_APP_SYFOREST_ROOT: "/syforest"
              run: |
                npm run build
              working-directory: ./client
            - name: Build and publish Docker image
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                docker build --tag ${IMAGE} .
                docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
                docker push ${IMAGE}
            - name: Deploy app to labs-gcp
              uses: nais/deploy/actions/deploy@master
              env:
                APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
                CLUSTER: labs-gcp
                RESOURCE: naiserator-demo.yml